<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [1]:

r1=int(input(" enter the first row "))
c1=int(input(" enter the first column "))
r2=int(input(" enter the second row "))
c2=int(input(" enter the second column "))
print()
print(" enter the elements of matrix 1 ") # for input of elements of matrix 1
a=[[int(input())for i in range(c1)] for j in range(r1)]
print(" enter the lements of second matrix 2 ")
b=[[int(input())for i in range(c2)] for j in range(r2)] # for input of elements of matrix 2
print(" the first matrix is ") #printing the first matrix
for i in range(r1):
    for j in range(c1):
        print(a[i][j],end=' ')
    print()
print(" the second matrix is ") #printing the second matrix
for i in range(r2):
    for j in range(c2):
        print(b[i][j],end=' ')
    print()
def matrix_mul(a,b,r1,c1,r2,c2):
    ab=[[0 for i in range(c2)]for j in range(r1)]
    if r2==c1:# to check whether the matrix are compatible or not
        for i in range(r1):       #multiplying matrices 1 and 2
            for j in range(c2):
                for k in range(c1):
                    ab[i][j]+=a[i][k]*b[k][j]
        print(" the result is")  # printing the resultant matrix
        for i in range(r1):
            for j in range(c2):
                print(ab[i][j],end=' ')
            print()


    else:                        #for the matrices which arenot compatible
        print("not possible")

matrix_mul(a,b,r1,c1,r2,c2)
    
    






 enter the first row 2
 enter the first column 2
 enter the second row 2
 enter the second column 5

 enter the elements of matrix 1 
1
2
3
4
 enter the lements of second matrix 2 
1
2
3
4
5
5
6
7
8
9
 the first matrix is 
1 2 
3 4 
 the second matrix is 
1 2 3 4 5 
5 6 7 8 9 
 the result is
11 14 17 20 23 
23 30 37 44 51 


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [18]:
import random
from random import uniform
a=[0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
def pick_random_no(a): #functiomn to pick the random number
    sum=0
    for i in a:
        sum+=i
    b=[i/sum for i in a ] 
    cf=[]
    c=b[0]
    cf.append(b[0])
    n=0
    for i in range(len(a)-1):
        c+=b[i+1]
        cf.append(c)
    r=random.uniform(0,1)
    for i in range(len(a)):
        if(r<=cf[i]):
            n=a[i]
            break
    return n
def trial(n): #function to conduct the experiment 100 times
    l=[]
    for i in range(1,n+1):
        p=pick_random_no(a)
        l.append(p)
    print(l)
trial(100)


        
        
        
    
    

    







[79, 79, 79, 28, 100, 28, 100, 79, 100, 10, 27, 100, 27, 5, 79, 79, 45, 100, 13, 100, 100, 100, 45, 45, 79, 45, 27, 100, 100, 100, 45, 100, 100, 45, 79, 79, 100, 100, 79, 79, 79, 45, 100, 45, 10, 6, 13, 79, 79, 27, 79, 79, 79, 100, 79, 100, 28, 79, 45, 100, 79, 28, 45, 28, 100, 100, 100, 45, 79, 79, 100, 100, 45, 79, 100, 45, 45, 27, 79, 27, 79, 100, 79, 28, 28, 28, 10, 79, 79, 45, 79, 79, 79, 45, 10, 27, 100, 79, 100, 100]


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [5]:
def replace_digits(string):
    for ele in string:
        if (ele.isdigit()): # for checking the digits in the string
            print("#",end='')
string=input(" enter the string here ")
replace_digits(string)
        

 enter the string here a2b3c4
###

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [29]:
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
d=dict(zip(Students,Marks))
d=sorted(d.items(),key=lambda x:x[1],reverse=True) 
print(" the top five ranks with decreasing marks  ")
for i in range(5): 
    print(d[i][0],end=' ')
    print(d[i][1])
print("\n")
print(" last five ranks in increasing order are")
for i in range(9,4,-1):
    print(d[i][0],end=' ')
    print(d[i][1])
print("\n")
print(" the order is between 25 percentile to 75 percentile ")
for i in range(6,1,-1):# the question should be not percentile but percentage
    print(d[i][0],end=' ')
    print(d[i][1])
# the percentage ouput is:
print('\n')
print(" the percentage output according to the question is ")
for i in d[::-1]:
    if(i[1]>25) and(i[1]<75):
        print(i[0],end=' ')
        print(i[1])
    

    
    

 the top five ranks with decreasing marks  
student8 98
student10 80
student2 78
student5 48
student7 47


 last five ranks in increasing order are
student3 12
student4 14
student9 35
student6 43
student1 45


 the order is between 25 percentile to 75 percentile 
student6 43
student1 45
student7 47
student5 48
student2 78


 the percentage output according to the question is 
student9 35
student6 43
student1 45
student7 47
student5 48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [22]:
# function created to find the five closest points from the list S from P(3,-4)
import math
import ast
def closest_points_to_p(s,p):
    b=[]
    for i in range(len(s)): # to compute the cosine distance
        d = math.acos(((s[i][0]*p[0])+(s[i][1]*p[1]))/((math.sqrt((s[i][0]**2)+(s[i][1]**2))) *(math.sqrt((p[0]**2)+(p[1]**2)))))
        b.append(d)
    
    d=dict(zip(s,b))
    d=sorted(d.items(),key=lambda x:x[1])
    d=d[:5]
    d=[d[i][0]for i in range(len(d))]
    return d
    
    
s=ast.literal_eval(input(" enter the values of s "))
p=ast.literal_eval(input(" enter the values of p "))
closest_points_to_p(s,p)
        
        
        

 enter the values of s [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
 enter the values of p (3,-4)


[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]

<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [2]:
import math
import re
import ast
def i_am_the_one(Red,Blue,Lines):
    rr=[]
    bb=[]
    for line in Lines:
        R=[]
        B=[]
        a, b, c = [float(x) for x in re.split('x|y', line)] #to get the coeffiecients of x,y,c
        for i in Red:
            r=a*i[0]+b*i[1]+c     # to make a list of the values of the given points
            R.append(r)
        rr.append(R)
        for i in Blue:
            d=a*i[0]+b*i[1]+c
            B.append(d)
        bb.append(B)

    for j in range(len(rr)): # to check whether the values are positive or negative
        r=[1 if i>0 else 0 for i in rr[j]]
        b=[1 if i>0 else 0 for i in bb[j]]
        if len(set(r))==1 and len(set(b))==1: # to compare the values for opposite signs
            if set(r)!=set(b):
                print("Yes")
            else:
                print("No")
        else:
            print("No")
red=ast.literal_eval(input())   # to input the values in red,blue and lines
blue=ast.literal_eval(input())
lines=ast.literal_eval(input())
i_am_the_one(red,blue,lines)  

[(1,1),(2,1),(4,2),(2,4), (-1,4)]
[(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
Yes
No
No
Yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [1]:
def curve_smoothin(s):
    s=s.split(",")
    c=0
    m=0
    #First Elements
    if s[-1]=="_" and s[0].isdigit():
        v=float(s[0])//len(s)
        for i in range(len(s)):
            s[i]=v
        return s
    else:
    
        for i in range(len(s)):
            if s[i]=="_":
                c+=1
            else:
                for j in range(0,i+1):
                    s[j]=str(float(s[i])/(c+1))
                m=i
                mv=float(s[i])
                break
        if len(s)-1==m:
            return s
        else:
        #Middle elements
            k=0
            a=1
            for i in range(m+1,len(s)):
                if s[i].isdigit():
                    a=i+1-m
                    k=i
                    break
            v=(mv+float(s[k]))//a
            for i in range(m,k+1):
                s[i]=v
            #Last Elements
            c=0
            for i in range(k+1,len(s)):
                if s[i]=="_":
                    c+=1
            lv=v//(c+1)
            for i in range(k,len(s)):
                s[i]=lv
            return s
strings = ["_,_,_,24","40,_,_,_,60","80,_,_,_,_","_,_,30,_,_,_,50,_,_"]

for s in strings:
    print (curve_smoothin(s))

        


['6.0', '6.0', '6.0', '6.0']
[20.0, 20.0, 20.0, 20.0, 20.0]
[16.0, 16.0, 16.0, 16.0, 16.0]
['10.0', '10.0', 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [8]:
import ast
def compute_conditional_probabilities(A):
    F=[A[i][0] for i in range(len(A))]
    S=[A[i][1] for i in range(len(A))]
    a=["{}{}".format(A[i][0],A[i][1]) for i in range(len(A))]
    ds={}
    for i in S:
        if i not in ds:
            ds[i]=1
        else:
            ds[i]+=1
    for i in a:
        if i[2:]=="S1":
            for j in range(1,6):
                c=0
                if ("F"+str(j)+"S1") in a:
                    c+=1
                print("P(F=F{}|S==S1)={}/{}".format(str(j),c,ds["S1"]))
            break

    print()
    for i in a:
        if i[2:]=="S2":
            for j in range(1,6):
                c=0
                if ("F"+str(j)+"S2") in a:
                    c+=1
                print("P(F=F{}|S==S2)={}/{}".format(str(j),c,ds["S2"]))
            break

    print()
    for i in a:
        if i[2:]=="S3":
            for j in range(1,6):
                c=0
                if ("F"+str(j)+"S3") in a:
                    c+=1
                print("P(F=F{}|S==S3)={}/{}".format(str(j),c,ds["S3"]))
            break
A=ast.literal_eval(input())
compute_conditional_probabilities(A)

[['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
P(F=F1|S==S1)=1/4
P(F=F2|S==S1)=1/4
P(F=F3|S==S1)=0/4
P(F=F4|S==S1)=1/4
P(F=F5|S==S1)=1/4

P(F=F1|S==S2)=1/3
P(F=F2|S==S2)=1/3
P(F=F3|S==S2)=1/3
P(F=F4|S==S2)=0/3
P(F=F5|S==S2)=0/3

P(F=F1|S==S3)=0/3
P(F=F2|S==S3)=1/3
P(F=F3|S==S3)=1/3
P(F=F4|S==S3)=1/3
P(F=F5|S==S3)=0/3


<h3> Q9: Given two sentences S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [4]:
def  string_features(s1,s2):
    a=0
    s1=s1.split()
    s2=s2.split()
    for i in s1: # to check the common words in setences s1 and s2
        for j in s2:
            if i==j:
                a=a+1
    print(a)
    b=[]
    c=[]
    for i in s1: # to check the elements in the sentence s1 and not in s2
        if i not in s2:
            b.append(i)
    for j in s2: # to check the sentences in the sentence s2 and not in s1
        if j not in s1:
            c.append(j)
    print(b)
    print(c)
    
s1=input(" enter the first sentence  ")
s2=input(" enter the second sentence  ")
string_features(s1,s2)

    

 enter the first sentence  the first column F will contain only 5 uniques values
 enter the second sentence  the second column S will contain only 3 uniques values
7
['first', 'F', '5']
['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [8]:
import math
import ast
def compute_log_loss(a):
    sum=0
    for i in range(8):
        
            sum+=a[i][0]*math.log10(a[i][1])+(1-a[i][0])*math.log10(1-a[i][1]) # for the sum of the logarithimaic series
    sum=-sum/len(a)
    return sum
a=ast.literal_eval(input(" enter the values of a  "))
print(compute_log_loss(a))
        
    
    
                

 enter the values of a  [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
0.42430993457031635
